export const FETCH_RECIPES_BY_SEARCH_INITIATE = "FETCH_RECIPES_BY_SEARCH_INITIATE";
export const FETCH_RECIPES_BY_SEARCH_SUCCESS = "FETCH_RECIPES_BY_SEARCH_SUCCESS";
export const FETCH_RECIPES_BY_SEARCH_FAIL = "FETCH_RECIPES_BY_SEARCH_FAIL";

export const FETCH_RECIPES_BY_CUISINE_INITIATE = "FETCH_RECIPES_BY_CUISINE_INITIATE";
export const FETCH_RECIPES_BY_CUISINE_SUCCESS = "FETCH_RECIPES_BY_CUISINE_SUCCESS";
export const FETCH_RECIPES_BY_CUISINE_FAIL = "FETCH_RECIPES_BY_CUISINE_FAIL";

export const FETCH_RECIPE_BY_ID_INITIATE = "FETCH_RECIPE_BY_ID_INITIATE";
export const FETCH_RECIPE_BY_ID_SUCCESS = "FETCH_RECIPE_BY_ID_SUCCESS";
export const FETCH_RECIPE_BY_ID_FAIL = "FETCH_RECIPE_BY_ID_FAIL";

export const FETCH_RECIPE_DETAILS_INITIATE = "FETCH_RECIPE_BY_ID_INITIATE";
export const FETCH_RECIPE_DETAILS_SUCCESS = "FETCH_RECIPE_BY_ID_SUCCESS";
export const FETCH_RECIPE_DETAILS_FAIL = "FETCH_RECIPE_BY_ID_FAIL";